language: go
go_import_path: github.com/newrelic/newrelic-telemetry-sdk-go

matrix:
  include:
  - go: "1.7"
  - go: "1.8"
  - go: "1.9"
  - go: "1.10"
  - go: "1.11"
  - go: "1.12"
  - go: "1.13"
    env: LATEST_VERSION=true

# Skip the install step. Don't `go get` dependencies.
install: true

script:
  - bash build-script.sh
